# ======================== Elasticsearch Configuration =========================
# xpack.security.enabled: false
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Elasticsearch bulk queue size -----------------------------------
thread_pool:
    bulk:
      queue_size: 2000

# ---------------------------------- X-PACK -----------------------------------
#action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*,logs-*,access-*

#-------------------------------------------- SEARCH GUARD Configuration ------------------

# ---------------------------------- Cluster -----------------------------------
#

# Use a descriptive name for your cluster:
#
cluster.name: es_cluster
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: master
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
# path.logs: /var/log/elasticsearch

# Path backup
# path.repo: /opt/repo_snapshots
index.codec: best_compression



#-------------------------------- AWS S3 configuration--------------------------
# s3.client.default.endpoint: 192.168.1.43:6007
# s3.client.default.protocol: "http"


# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
http.enabled: true
transport.tcp.port: 9300
network.host: 0.0.0.0
network.bind_host: 0
client.transport.sniff: true
http.compression: true
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Search GUARD -----------------------------------

# WARNING: revise all the lines below before you go into production
# searchguard.enterprise_modules_enabled: false
# searchguard.ssl.transport.enabled: true
# searchguard.ssl.transport.keystore_filepath: sgconfig/node-0-keystore.jks
# searchguard.ssl.transport.truststore_filepath: sgconfig/truststore.jks
# searchguard.ssl.transport.enforce_hostname_verification: filtered_alias_mode
#
# searchguard.ssl.http.enabled: true
# searchguard.ssl.http.keystore_filepath: sgconfig/node-0-keystore.jks
# searchguard.ssl.http.truststore_filepath: sgconfig/truststore.jks
# searchguard.authcz.admin_dn:
#  - CN=kirk,OU=client,O=client,L=Test,C=DE
#
# searchguard.audit.type: internal_elasticsearch
# searchguard.enable_snapshot_restore_privilege: true
# searchguard.check_snapshot_restore_write_privileges: true
# searchguard.restapi.roles_enabled: ["sg_all_access"]
# cluster.routing.allocation.disk.threshold_enabled: false
# node.max_local_storage_nodes: 3
######## End Search Guard Demo Configuration ########
